spring.application.name=pcfactory
spring.datasource.url=jdbc:mysql://localhost:3306/pcfactory
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
webpay.commerce-code=597055555532
webpay.api-key=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
webpay.base-url=https://webpay3gint.transbank.cl